### ISSUE TITLE
Intent Configuration

### ISSUE THREAD

**Issue by jklaiber** [hawkv6/hawkwing#2]
Add configuration possibilities for the intent:

It could be for example:
```yaml
intents:
    web-b.hawk.net:
        intent: high-bandwidth   
    db-c.hawk.net:
        intent: high-bandwidth
        traffic-control: 
            - fcbb:bb00:1::1
            - fcbb:bb00:1::3
```
